<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\SiteMapItem;


/**
 * SiteMapItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteMapItemRepository extends EntityRepository
{
  public function getChildren(SiteMapItem $item)
  {
    
  }
  
}
