<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Text;
/**
 * TextTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextTranslationRepository extends EntityRepository
{
  public function getTranslation(Text $text, %local)
  {
  }
}
